var rule = {
  title: '奶香',
  host: 'https://naixxzy.com',
  homeTid: '13',
  homeUrl: '/api.php/provide/vod/?ac=detail&t={{rule.homeTid}}',
  detailUrl: '/api.php/provide/vod/?ac=detail&ids=fyid',
  searchUrl: '/api.php/provide/vod/?wd=**&pg=fypage',
  url: '/api.php/provide/vod/?ac=detail&pg=fypage&t=fyclass',
  headers: {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36',
  },
  timeout: 5000,
  class_parse: 'json:class;',
  cate_exclude:'精品国产|精品日韩|精品综合|精品小说|精品美图',
  limit: 20,
  multi: 1,
  searchable: 2,
  quickSearch: 1,
  filterable: 0,
  play_parse: true,
  parse_url: '',
  lazy: "js:\n  if (/\\.(m3u8|mp4)/.test(input)) {\n    input = { parse: 0, url: input };\n  } else {\n    if (rule.parse_url.startsWith('json:')) {\n      let purl = rule.parse_url.replace('json:', '') + input;\n      let html = request(purl);\n      let json = JSON.parse(html);\n      if (json.url) {\n        input = { parse: 0, url: json.url };\n      }\n    } else {\n      input = rule.parse_url + input;\n    }\n  }",
  推荐: '*',
  一级: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_play_from',
  二级: 'js:\n            let html=request(input);\n            html=JSON.parse(html);\n            let data=html.list;\n            VOD=data[0];',
  搜索: '*',
}